# Generated by Django 5.1.1 on 2024-09-28 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="children",
            name="homework_voice",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="children",
            name="personal_voice",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
