# Generated by Django 5.1.1 on 2024-09-28 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.CharField(max_length=255),
        ),
    ]
