# Generated by Django 5.1.1 on 2024-09-29 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_children_homework_voice_children_personal_voice"),
    ]

    operations = [
        migrations.AddField(
            model_name="children",
            name="fin_voice",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
